using InternalManagement.Domain.Enums;

namespace InternalManagement.Application.Features.HrPayroll.DTOs;

public record EmployeeDto(
    Guid Id,
    Guid CompanyId,
    Guid? BusinessUnitId,
    string? BusinessUnitName,
    Guid? DepartmentId,
    string? DepartmentName,
    Guid? UserId,
    string? Username,
    string EmployeeCode,
    string FullName,
    string Email,
    string? Phone,
    string? Position,
    decimal BaseSalary,
    DateTime? JoinedDate,
    string Status,
    DateTime CreatedAt,
    EmploymentType EmploymentType = EmploymentType.FULL_TIME,
    string EmploymentTypeNameVi = "Toàn thời gian",
    PartTimeCalculationMethod? PartTimeCalculationMethod = null,
    string? PartTimeCalculationMethodNameVi = null,
    decimal? PartTimeUnitRate = null,
    string? CvUrlOrPath = null,
    string? ProfessionalSummary = null,
    string? Skills = null,
    string? Experience = null,
    DateTime? StatusChangedAt = null,
    string? StatusReason = null);

public record EmployeeDetailDto(
    Guid Id,
    Guid CompanyId,
    Guid? BusinessUnitId,
    string? BusinessUnitName,
    Guid? DepartmentId,
    string? DepartmentName,
    Guid? UserId,
    string? Username,
    string EmployeeCode,
    string FullName,
    string Email,
    string? Phone,
    string? Position,
    decimal BaseSalary,
    DateTime? JoinedDate,
    string Status,
    DateTime CreatedAt,
    int AttendanceCount,
    int PayslipCount,
    EmploymentType EmploymentType = EmploymentType.FULL_TIME,
    string EmploymentTypeNameVi = "Toàn thời gian",
    PartTimeCalculationMethod? PartTimeCalculationMethod = null,
    string? PartTimeCalculationMethodNameVi = null,
    decimal? PartTimeUnitRate = null,
    string? CvUrlOrPath = null,
    string? ProfessionalSummary = null,
    string? Skills = null,
    string? Experience = null,
    DateTime? StatusChangedAt = null,
    string? StatusReason = null);

public record CreateEmployeeRequest(
    string EmployeeCode,
    string FullName,
    string Email,
    string? Phone,
    string? Position,
    decimal BaseSalary,
    Guid? DepartmentId = null,
    Guid? BusinessUnitId = null,
    DateTime? JoinedDate = null,
    string Status = "Active",
    EmploymentType EmploymentType = EmploymentType.FULL_TIME,
    PartTimeCalculationMethod? PartTimeCalculationMethod = null,
    decimal? PartTimeUnitRate = null,
    string? CvUrlOrPath = null,
    string? ProfessionalSummary = null,
    string? Skills = null,
    string? Experience = null,
    DateTime? StatusChangedAt = null,
    string? StatusReason = null,
    Guid? UserId = null);

public record UpdateEmployeeRequest(
    string FullName,
    string Email,
    string? Phone,
    string? Position,
    decimal BaseSalary,
    Guid? DepartmentId = null,
    Guid? BusinessUnitId = null,
    DateTime? JoinedDate = null,
    string Status = "Active",
    EmploymentType? EmploymentType = null,
    PartTimeCalculationMethod? PartTimeCalculationMethod = null,
    decimal? PartTimeUnitRate = null,
    string? CvUrlOrPath = null,
    string? ProfessionalSummary = null,
    string? Skills = null,
    string? Experience = null,
    DateTime? StatusChangedAt = null,
    string? StatusReason = null,
    Guid? UserId = null);
